#!/usr/bin/env bash

wallpaper_folder=$HOME/Pictures/wallpapers
wallpaper_location="$(ls $wallpaper_folder | wofi -n --show dmenu -k "/dev/null")"

echo "$wallpaper_folder/$wallpaper_location"

if [[ -d $wallpaper_folder/$wallpaper_location ]]; then
	echo "$wallpaper_folder/$wallpaper_location is a directory"
	wallpaper_temp="$wallpaper_location"
	sleep 2
	wallpaper_location="$(ls $wallpaper_folder/$wallpaper_location | wofi -n --show dmenu -k "/dev/null")"
elif [[ -f $wallpaper_folder/$wallpaper_location ]]; then
	echo "$wallpaper_folder/$wallpaper_location is a file"
else 
	echo "$wallpaper_folder/$wallpaper_location is not valid"
	exit 1
fi

file="$wallpaper_folder/$wallpaper_temp/$wallpaper_location"

echo "preload = $file" > $HOME/.config/hypr/hyprpaper.conf
echo "wallpaper = DP-2,$file" >> $HOME/.config/hypr/hyprpaper.conf
echo "wallpaper = HDMI-A-1,$file" >> $HOME/.config/hypr/hyprpaper.conf
